export const dict = {
  "weapons": "Оружие",
  "shells": "Оболочки",
  "assault rifle": "Штурмовая винтовка",
  "sniper rifle": "Снайперская винтовка",
  "precision rifle": "Марксманская винтовка",
  "shotgun": "Дробовик",
  "smg": "Пистолет-пулемет",
  "lmg": "Пулемет",
  "pistol": "Пистолет",
  "standard": "Стандарт",
  "standard assault rifle": "Стандартная штурмовая винтовка",
  "standard precision rifle": "Стандартная марксманская винтовка",
  "standard sniper rifle": "Стандартная снайперская винтовка",
  "standard shotgun": "Стандартный дробовик",
  "damage": "Урон",
  "weight": "Вес",
  "firepower": "Огневая мощь",
  "accuracy": "Точность",
  "handling": "Удобство",
  "range": "Дальность",
  "magazine": "Магазин",
  "zoom": "Увеличение",
  "hipfire_spread": "Разброс от бедра",
  "ads_spread": "Разброс в прицеле",
  "crouch_spread_bonus": "Бонус разброса (сидя)",
  "moving_inaccuracy": "Штраф в движении",
  "equip_speed": "Скорость экипировки",
  "ads_speed": "Скорость прицеливания",
  "recoil": "Отдача",
  "aim_assist": "Помощь в прицеливании",
  "reload_speed": "Скорость перезарядки",
  "precision_multiplier": "Множитель в голову",
  "rate_of_fire": "Скорострельность",
  "ammo": "Тип патронов",
  "firing_mode": "Режим стрельбы",
  "weapon_type": "Тип оружия",
  "base_heat": "Базовая теплоемкость",
  "role": "Роль",
  "optic": "Оптика",
  "barrel": "Ствол",
  "muzzle": "Дуло",
  "chip": "Чип",
  "stock": "Приклад",
  "single round": "Одиночными",
  "full auto": "Автоматический",
  "heavy rounds": "Тяжелые патроны",
  "light rounds": "Легкие патроны",
  "energy rounds": "Энерго-ячейки",
  "archetype": "Архетип",
  "tech": "Технология",
  "model": "Модель",
  "series": "Серия",
  "gender": "Пол",
  "description": "Описание",
  "shadow agent": "Теневой агент",
  "invisibility systems": "Системы невидимости",
  "male": "Мужской",
  "female": "Женский",
  "heat_capacity": "Теплоемкость",
  "agility": "Маневренность",
  "loot_speed": "Скорость сбора лута",
  "melee_damage": "Урон в ближнем бою",
  "prime_recovery": "Восстановление Прайм-навыка",
  "tactical_recovery": "Восстановление Тактич. навыка",
  "self_repair_speed": "Скорость саморемонта",
  "finisher_siphon": "Вампиризм добивания",
  "revive_speed": "Скорость воскрешения",
  "hardware": "Аппаратное обеспечение",
  "firewall": "Файрвол",
  "fall_resistance": "Сопротивление падению",
  "ping_duration": "Длительность метки",
  "head": "Голова",
  "torso": "Торс",
  "legs": "Ноги",
  "shield": "Щит",
  "arms": "Руки",

  // Типы способностей
  "prime ability": "Прайм-способность",
  "tactical ability": "Тактическая способность",
  "trait 1": "Особенность 1",
  "trait 2": "Особенность 2"
};

export const t = (key) => {
  if (!key) return '';
  const lowerKey = String(key).toLowerCase();
  return dict[lowerKey] || key;
};